<?php

namespace NK\PersoPageBundle\Repository;

/**
 * ProfessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessorRepository extends \Doctrine\ORM\EntityRepository
{
}
