<?php

namespace NK\PersoPageBundle\Repository;

/**
 * PublishedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishedDataRepository extends \Doctrine\ORM\EntityRepository
{
}
