<?php

namespace NK\PersoPageBundle\Repository;

/**
 * SavedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavedDataRepository extends \Doctrine\ORM\EntityRepository
{
}
