<?php

namespace NK\PersoPageBundle\Repository;

/**
 * SexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SexRepository extends \Doctrine\ORM\EntityRepository
{
}
