nk_perso_page:
    resource: "@NKPersoPageBundle/Resources/config/routing.yml"
    prefix:   /pageperso

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
  resource: '@FOSUserBundle/Resources/config/routing/all.xml'