nk_perso_page_homepage:
    path:     /
    defaults: { _controller: NKPersoPageBundle:Default:index }

nk_perso_page_welcomePage:
    path:    /Accueil
    defaults: { _controller: NKPersoPageBundle:Accueil:accueil }